export const FETCH_CARS = 'MY-TEST/FETCH_CARS'
export const FETCH_CARS_SUCCESS = 'MY-TEST/FETCH_CARS_SUCCESS'
export const FETCH_CARS_FAILURE = 'MY-TEST/FETCH_CARS_FAILURE'

export const DELETE_CAR = 'MY-TEST/DELETE_CAR'
export const DELETE_CAR_SUCCESS = 'MY-TEST/DELETE_CAR_SUCCESS'
export const DELETE_CAR_FAILURE = 'MY-TEST/DELETE_CAR_FAILURE'

export const CREATE_CAR = 'MY-TEST/CREATE_CAR'
export const CREATE_CAR_SUCCESS = 'MY-TEST/CREATE_CAR_SUCCESS'
export const CREATE_CAR_FAILURE = 'MY-TEST/CREATE_CAR_FAILURE'

export const UPDATE_CAR = 'MY-TEST/UPDATE_CAR'
export const UPDATE_CAR_SUCCESS = 'MY-TEST/UPDATE_CAR_SUCCESS'
export const UPDATE_CAR_FAILURE = 'MY-TEST/UPDATE_CAR_FAILURE'

export const FETCH_FILTER = 'MY-TEST/FETCH_FILTER'
export const FETCH_FILTER_CARS_SUCCESS = 'MY-TEST/FETCH_FILTER_CARS_SUCCESS'
export const FETCH_FILTER_CARS_FAILURE = 'MY-TEST/FETCH_FILTER_CARS_FAILURE'




